### ISSUE TITLE
Can. not download YT video

### ISSUE THREAD

**Issue by knight2010** [VishwaiOSDev/Loadify-iOS#26] opened 2023-12-25 09:36 UTC
I tried recently, not work for yt download. Can you help to look at.

**Comment by VishwaiOSDev** [comment] 2024-01-04 03:06
Hi @knight2010,

Firstly, I appreciate your engagement with the project and your commitment to providing feedback. I noticed that you recently raised an issue on GitHub regarding difficulties with YouTube downloads.

I apologize for any inconvenience you may have experienced, and I would be more than happy to help resolve this matter. However, in order to assist you effectively, I kindly request that you provide more detailed information about the issue you encountered. Please consider including the following details:

1. The steps you followed to reproduce the problem.
2. Any error messages or warnings you received during the process.
3. Screenshots, if possible, to help visualize the issue.
4. The version of the application or tool you are using.
5. Any additional context or specific scenarios where you encountered the problem.

By providing this information, you will greatly assist me in identifying and addressing the root cause of the issue. Rest assured, I am committed to ensuring that the app functions as intended and providing a seamless experience for all users.

If you could submit the requested details within the next 15 days, it would greatly aid in expediting the resolution process. However, if the issue has been resolved on your end or if you encounter any challenges in providing the information, please feel free to let me know.

Thank you for your collaboration and understanding. I look forward to working together to ensure the tool meets your expectations.

**Closed** 2024-01-07 21:06 UTC
